params:
    interpolation_delay: .1
    use_smoothing_interpolator: true
ros_topics:
    joint_state: /robot/joint_state # Only used by main().
    rmpflow_commands: 
        command: /rmpflow/commands/joint_command
        ack: /rmpflow/commands/joint_command/ack
        suppress: /rmpflow/commands/joint_command/suppress
        interpolated: /rmpflow/commands/joint_command/interpolated
